HeadNode:
  InstanceType: g4dn.xlarge
  Ssh:
    KeyName: ${SSH_KEY_NAME}
  Networking:
    SubnetId: subnet-xxxxxxxxxxx
  LocalStorage:
    RootVolume:
      Size: 200
      VolumeType: gp3
  Dcv:
    Enabled: true
    AllowedIps: 0.0.0.0/0
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
  Imds:
    Secured: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: compute
          MinCount: 0
          MaxCount: 2
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false
          Instances:
            - InstanceType: p3.16xlarge
      Networking:
        SubnetIds:
          - subnet-yyyyyyyyyy
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 200
            VolumeType: gp3
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpc-${AWS_ACCOUNT}-${AWS_REGION}-${USER_NAME}/container-install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      AllocationStrategy: lowest-price
  SlurmSettings: {}
Region: ${AWS_REGION}
Image:
  Os: ubuntu2004
  CustomAmi: ${CUSTOM_AMI}
SharedStorage:
  - Name: Ebs0
    StorageType: Ebs
    MountDir: /shared
    EbsSettings:
      Size: 200
      VolumeType: gp3
      DeletionPolicy: Delete
  - Name: Fsx0
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 1200
      PerUnitStorageThroughput: 125
#      ImportPath: s3://hpc-${AWS_ACCOUNT}-${AWS_REGION}-${USER_NAME}
      DeploymentType: PERSISTENT_2
      DataCompressionType: LZ4
      DeletionPolicy: Delete
Imds:
  ImdsSupport: v2.0
