HeadNode:
  InstanceType: m6i.large
  Ssh:
    KeyName: ${SSH_KEY_NAME}
  Networking:
    SubnetId: subnet-xxxxxxxxxxx
  LocalStorage:
    RootVolume:
      Size: 50
      VolumeType: gp3
  Dcv:
    Enabled: true
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
  Imds:
    Secured: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: compute
          MinCount: 0
          MaxCount: 2
          InstanceType: c6i.16xlarge
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-yyyyyyyyyy
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 50
            VolumeType: gp3
      CustomActions:
        OnNodeConfigured:
          Script: s3://hpc-${AWS_ACCOUNT}-${AWS_REGION}-${USER_NAME}/container-install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
Region: ${AWS_REGION}
Image:
  Os: ubuntu2204
#  CustomAmi: ${CUSTOM_AMI}
SharedStorage:
  - Name: Ebs0
    StorageType: Ebs
    MountDir: /shared
    EbsSettings:
      Size: 50
      VolumeType: gp3
      DeletionPolicy: Delete
  - Name: Fsx0
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 1200
      PerUnitStorageThroughput: 125
      ImportPath: s3://hpc-${AWS_ACCOUNT}-${AWS_REGION}-${USER_NAME}
      DeploymentType: PERSISTENT_2
      DataCompressionType: LZ4
      DeletionPolicy: Delete
