HeadNode:
  InstanceType: m6i.xlarge
  Ssh:
    KeyName: ec2-key-pair
  Networking:
    SubnetId: subnet-xxxxxxxxxxx1234567
  LocalStorage:
    RootVolume:
      Size: 50
      VolumeType: gp3
      Encrypted: true
  Dcv:
    Enabled: true
    AllowedIps: 0.0.0.0/0
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Imds:
    Secured: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: compute
          MinCount: 0
          MaxCount: 4
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false
          Instances:
            - InstanceType: p3.8xlarge
      Image:
        CustomAmi: ami-zzzzzzzzzz1234567
      Networking:
        SubnetIds:
          - subnet-yyyyyyyyyy1234567
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
            VolumeType: gp3
            Encrypted: true
      CustomActions:
        OnNodeConfigured:
          Script: >-
            s3://hpc-123456789012-us-west-2-username/on-node-configured-install.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3FullAccess
      AllocationStrategy: lowest-price
  SlurmSettings: {}
Region: us-west-2
Image:
  Os: ubuntu2004
Imds:
  ImdsSupport: v2.0
SharedStorage:
  - Name: hpc-efs
    StorageType: Efs
    MountDir: /mnt/efs/fs1
    EfsSettings:
      FileSystemId: fs-zzzzzzzzzz1234567
