HeadNode:
  InstanceType: c5a.2xlarge
  Ssh:
    KeyName: wangrob-migration-sandbox-08-us-east-2
  Networking:
    SubnetId: subnet-0bd5509006b9f29b9
  LocalStorage:
    RootVolume:
      Size: 40
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  Dcv:
    Enabled: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: c5n
          MinCount: 0
          MaxCount: 64
          InstanceType: c5n.18xlarge
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-0bd5509006b9f29b9
        PlacementGroup:
          Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Region: us-east-2
Image:
  Os: alinux2
  