HeadNode:
  InstanceType: c5a.2xlarge
  Ssh:
    KeyName: wangrob-sandbox-08-ec2-us-west-2
  Networking:
    SubnetId: subnet-0ac3b527a915aac66
  LocalStorage:
    RootVolume:
      Size: 40
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  Dcv:
    Enabled: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      ComputeResources:
        - Name: c5n
          MinCount: 0
          MaxCount: 64
          InstanceType: c5n.18xlarge
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-0ac3b527a915aac66
          - subnet-05ae8c5b287342668
        PlacementGroup:
          Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Region: us-west-2
Image:
  Os: alinux2
  